param(
  [string]$Assets = (Join-Path $PSScriptRoot '..\.cache\vscodium\assets'),
  [switch]$SkipNotices
)

# Emits the provenance attestation and the third-party license notice from what
# actually shipped.
#
# Everything here is derived from the build manifest, `sources.lock.json`, and
# the packaged editor on disk. Nothing is hand-written: if an input is missing
# or disagrees with another, this throws rather than emitting a plausible file.
#
# Note this is a *build record*, not a signature. It makes claims about what was
# produced; it does not prove them to a third party. Only a code signature would
# do that, and there is none.
$ErrorActionPreference = 'Stop'
$root = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot '..')).Path
$assetsPath = (Resolve-Path -LiteralPath $Assets).Path
$utf8 = [System.Text.UTF8Encoding]::new($false)

$manifestPath = Join-Path $assetsPath 'build-manifest.json'
if (!(Test-Path -LiteralPath $manifestPath)) { throw "No build manifest at $manifestPath." }
$manifest = Get-Content -Raw -LiteralPath $manifestPath | ConvertFrom-Json
$lock = Get-Content -Raw -LiteralPath (Join-Path $root 'sources.lock.json') | ConvertFrom-Json
$editor = Join-Path $assetsPath '..\VSCode-win32-x64'

if (!$manifest.builtFromCommit) {
  throw 'The manifest records no builtFromCommit. Rebuild with scripts/build-m1.ps1.'
}

# Recompute every digest rather than copying it, so a corrupted artifact cannot
# be blessed by re-reading the file that describes it.
$artifactFacts = foreach ($artifact in $manifest.artifacts) {
  $file = Join-Path $assetsPath $artifact.name
  if (!(Test-Path -LiteralPath $file)) { throw "Artifact missing: $($artifact.name)" }
  $actual = (Get-FileHash -LiteralPath $file -Algorithm SHA256).Hash.ToLowerInvariant()
  [ordered]@{
    name     = $artifact.name
    bytes    = (Get-Item -LiteralPath $file).Length
    sha256   = $actual
    drifted  = ($actual -ne $artifact.sha256.ToLowerInvariant())
  }
}
$drift = @($artifactFacts | Where-Object { $_.drifted })
if ($drift.Count -gt 0) {
  throw "Artifact digest does not match the manifest: $(($drift | ForEach-Object { $_.name }) -join ', ')"
}
$attestation = [ordered]@{
  schemaVersion   = 1
  generatedBy     = 'scripts/gen-provenance.ps1'
  attestationKind = 'unsigned-build-record'
  signed          = $false
  published       = $false
  desktopVersion  = $manifest.desktopVersion
  builtFromCommit = $manifest.builtFromCommit
  target          = $manifest.target
  sources         = [ordered]@{
    vscodium = [ordered]@{ commit = $manifest.sources.vscodium; tag = $lock.sources.vscodium.tag; repository = $lock.sources.vscodium.repository }
    codeOss  = [ordered]@{ commit = $manifest.sources.codeOss; tag = $lock.sources.codeOss.tag; repository = $lock.sources.codeOss.repository }
    moderado = [ordered]@{ commit = $manifest.pinnedAgentRevisionForMilestone2; tag = $lock.sources.moderado.tag; repository = $lock.sources.moderado.repository }
  }
  artifacts       = @($artifactFacts | ForEach-Object {
    [ordered]@{ name = $_.name; bytes = $_.bytes; sha256 = $_.sha256 }
  })
}

# The notices must come from files that are really in the package. A notice that
# is not shipped is a compliance gap, not a documentation nicety.
$noticeFacts = @(
  [ordered]@{ id = 'chromium'; file = 'LICENSES.chromium.html' }
  [ordered]@{ id = 'code-oss'; file = 'LICENSE.txt' }
) | ForEach-Object {
  $path = Join-Path $editor $_.file
  [ordered]@{
    id     = $_.id
    file   = $_.file
    exists = (Test-Path -LiteralPath $path)
    bytes  = if (Test-Path -LiteralPath $path) { (Get-Item -LiteralPath $path).Length } else { 0 }
  }
}
$missing = @($noticeFacts | Where-Object { -not $_.exists })
if ($missing.Count -gt 0) {
  throw "Required license notice(s) absent from the packaged editor: $(($missing | ForEach-Object { $_.file }) -join ', ')"
}
$attestation.licenseNotices = @($noticeFacts)
[System.IO.File]::WriteAllText(
  (Join-Path $assetsPath 'provenance.json'),
  ($attestation | ConvertTo-Json -Depth 10),
  $utf8)

# The human-readable notice, generated so it cannot drift from the pins.
if (!$SkipNotices) {
  $chromium = ($noticeFacts | Where-Object { $_.id -eq 'chromium' }).bytes
  $codeOss  = ($noticeFacts | Where-Object { $_.id -eq 'code-oss' }).bytes
  $lines = @(
    '# Moderado Desktop third-party notices'
    ''
    'Generated by `scripts/gen-provenance.ps1`. Edit that script, not this file.'
    'It lists the upstream inputs this build was produced from.'
    ''
    '## Build identity'
    ''
    ("- Desktop version: {0}" -f $manifest.desktopVersion)
    ("- Built from commit: {0}" -f $manifest.builtFromCommit)
    ("- Target: {0}" -f $manifest.target)
    ''
    '## Code OSS / VSCodium'
    ''
    ("- Code OSS {0} ({1}), MIT licensed." -f $lock.sources.codeOss.tag, $manifest.sources.codeOss)
    ("- VSCodium {0} ({1}) build scripts and downstream configuration." -f $lock.sources.vscodium.tag, $manifest.sources.vscodium)
    ("- Full Chromium third-party notices ship as `LICENSES.chromium.html` ({0} bytes)." -f $chromium)
    ("- The editor license ships as `LICENSE.txt` ({0} bytes)." -f $codeOss)
    ''
    '## Moderado agent'
    ''
    ("- Vendored from {0} at {1}." -f $lock.sources.moderado.repository, $manifest.pinnedAgentRevisionForMilestone2)
    ("- Bundled at tag {0}." -f $lock.sources.moderado.tag)
    '- The vendored packages carry no `license` field in their `package.json`.'
    '  Moderado Desktop is distributed under the MIT license (see `LICENSE` at the'
    '  repository root). Confirm the agent license with the upstream project before'
    '  any public distribution.'
    ''
    '## Not present'
    ''
    '- No code signature. These artifacts are unsigned and there is no Authenticode'
    '  signature to validate.'
    '- No update channel. There is no configured update endpoint.'
    ''
  )
  [System.IO.File]::WriteAllText(
    (Join-Path $assetsPath 'THIRD-PARTY-NOTICES.md'),
    ($lines -join [Environment]::NewLine),
    $utf8)
}

Write-Output ("Wrote provenance.json ({0} artifacts){1}" -f @($artifactFacts).Count, $(if ($SkipNotices) { ' (notices skipped)' } else { ' and THIRD-PARTY-NOTICES.md' }))